### ISSUE TITLE
things you need to do

### ISSUE THREAD

**Issue by haniali1234** [geekwise-juston-miller/geekwise-academy#2]
- page: team
- issue: footer
  photo:
  ![screen shot 2016-03-18 at 11 51 28 am](https://cloud.githubusercontent.com/assets/11038599/13888699/03d0764a-ed00-11e5-8c1a-2befcc48a39d.png)

**Comment by geekwise-juston-miller** [comment]
@haniali1234 
I think I fixed this issue, check it out and let me know.
