### ISSUE TITLE
Linking Issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-juston-miller/geekwise-academy#3]
page: global
issue: links are broken

![screen shot 2016-03-18 at 3 41 11 pm](https://cloud.githubusercontent.com/assets/7436666/13893930/e13442ea-ed1f-11e5-95f8-4d85883c711c.png)

possibly an issue with GH-pages

**Comment by geekwise-juston-miller** [comment]
@Sramos9191 

all pages are linked now, but not all pages are finished.
